html-nri
ytaka0407/y.takashima pull request #1
Opened 2020-07-09 13:47 UTC by ytaka0407

NRI課題のHTMLファイルまでを作成しました。

2020-07-09 21:43 UTC, piasoratech requested changes
いくつか指摘しましたが、指摘した内容以外にもまだ修正すべき点は多くあります。
タグの役割の理解がまだ浅いように感じるので、教科書をもう一度見直したりしながら修正をしてみましょう。
また、エラーが発生している部分はタグが閉じられていなかったり、そもそも開けていないのに閉じられているみたいなものが多かったので、もう一度タグの対応を見直してください。

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +    <meta charset="UTF-8">
`meta`タグの`description`も追加しておきましょう

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +        nonce="I0ILxyZm"></script>
ここは何のために記述されているでしょうか？

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +                <img src="images/NRIlogo.jpg" alt="" width="70" height="35">
`img`タグの`alt`には重要な役割があるので、その画像が言葉で表せるものや意味のあるものであれば空欄にせずきちんと書く必要があります。
以下のサイトも見てみてください。
https://www.asobou.co.jp/blog/web/alt

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +                <div></div>
この`div`は何のために用意していますか？

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +            <a class="icon">
`a`タグを書くのであればリンク先も書きましょう。
今回の課題の場合、特定のリンク先を書く必要はなく`#`だけで大丈夫です。

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +    <p class="topicpath">NRI トップ <img src="images/arrowright.png" alt=""> 企業情報 &<img src="images/arrowright.png" alt="">
`main`タグを使いましょう

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +            <div>share</div>
`div`タグを使わない方がいいです

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +                        MB）</a></div>
この部分のインデントや書き方などきれいにしましょう

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +            <li><img src="images/arrowright.png" alt=""><a href="">社長メッセージ</a></li>
この辺りすべてそうですが、`>`は画像として埋め込むのではなく、疑似要素として付与する形にしましょう

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +</html>
最後に改行を入れてください

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +    </footer>
これより下の部分が`footer`になるかと

2020-07-09 21:43 UTC, piasoratech commented on takashima-nri.html
> +    <section id="copyright">
`copyright`はここから始まるわけではなく一番最後の部分だけなのでこの命名は適切ではないです。

2020-07-10 08:09 UTC, ytaka0407 commented on takashima-nri.html
> +    <meta charset="UTF-8">
追記しました。

2020-07-10 08:09 UTC, ytaka0407 commented on takashima-nri.html
> +        nonce="I0ILxyZm"></script>
すみません、facebookのシェアボタン作成時、シェアボタンのプラグインを入れるか迷い、中途半端に入れてしまっていました。一旦削除しました。

2020-07-10 08:10 UTC, ytaka0407 commented on takashima-nri.html
> +                <img src="images/NRIlogo.jpg" alt="" width="70" height="35">
ありがとうございます。リンク先のサイト読んでみます。
内容追記しました。

2020-07-10 08:16 UTC, ytaka0407 commented on takashima-nri.html
> +                <div></div>
三本線のメニュー部分です。画像では内容だったので調べてみて、下記のサイトを参考にcssで背景色をつけて配置を調整して実装しようと考えました。
https://webllica.com/humberger-menu-by-html-css/

2020-07-10 08:37 UTC, ytaka0407 commented on takashima-nri.html
> +            <a class="icon">
修正しました。リンクを張っていた部分も"＃"に一旦揃えました。

2020-07-10 09:12 UTC, ytaka0407 commented on takashima-nri.html
> +            <li><img src="images/arrowright.png" alt=""><a href="">社長メッセージ</a></li>
画像削除しました。cssにて擬似要素追記します。

2020-07-11 05:34 UTC, ytaka0407 commented on takashima-nri.html
> +    </footer>
再度見直し、タグを修正しました。あわせて中身でリストにあたる部分のタグを修正しました。

2020-07-11 05:35 UTC, ytaka0407 commented on takashima-nri.html
> +    <section id="copyright">
footerタグに修正・headerタグの命名に合わせて修正しました。

2020-07-11 05:37 UTC, ytaka0407 commented on takashima-nri.html
> +</html>
勉強不足ですみません。この場合の入れるべき改行とは、下記の形であっていますか？
<a href="#page">
<img src="images/gototop.png" alt="" width="60" height="60">
</a>
よろしくお願いします。

2020-07-11 06:06 UTC, ytaka0407 commented on takashima-nri.html
> +    <p class="topicpath">NRI トップ <img src="images/arrowright.png" alt=""> 企業情報 &<img src="images/arrowright.png" alt="">
ヘッダーフッター間の要素全体にmainタグ追記しました。

2020-07-11 06:12 UTC, ytaka0407 commented on takashima-nri.html
> +                        MB）</a></div>
修正しました。リンク内容は他と揃えて＃に置き換えました。

2020-07-11 06:13 UTC, ytaka0407 commented on takashima-nri.html
> +            <div>share</div>
削除しました。cssにて擬似要素追加します。

2020-07-13 08:39 UTC, kouyanh commented on takashima-nri.html
> +                <div></div>
画像で実装でも構わないとは思いますが、マークアップ（意味づけ）するための言語はHTMLなので、空タグはコード中に書かないようにしておいたほうが良いと思います。装飾に関するものはCSSで実装したほうがいいですね。意味があればHTMLにという感じで分けてあげましょう。

2020-07-13 14:28 UTC, spre55 commented on takashima-nri.html
> +</html>
多分ファイル末尾の改行のことだと思うので参考までに。

Githubで、ファイル末尾に改行がないと、<img width="26" alt="スクリーンショット 2020-07-13 23 04 49" src="https://user-images.githubusercontent.com/6168817/87315679-aa6c2300-c55f-11ea-8973-78689e4c684a.png">という赤いマークが出ます。

なぜそうなるか。かんたんに言うと、
「テキストファイルは本来（POSIX的には）必ず最後は改行コードで終わっていなければならない」というルールがあり、それが守られていないときに出る警告
ってことです。

以下に参考のリンクを貼っておきました。知っとくといいかなと思います。
https://www.cqpub.co.jp/interface/sample/200902/if02_038.pdf

標準規格やIEEE、POSIXなどについては知っておくとよいです。

標準化の精神に共感し、「私はPOSIX準拠で生きていくんだ！！！！」
という強い思いを芽生えさせ、身を奮い立たせてから直してみてください。

2020-07-15 08:24 UTC, ytaka0407 commented on takashima-nri.html
> +</html>
標準化の精神共感してきました！今後の生き方をを考えつつ修正しました。

2020-07-15 12:58 UTC, ytaka0407 commented on takashima-nri.html
> +                <div></div>
コメント入れられていませんでした。画像で実装に変更します！

2020-07-19 01:05 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-07-19 01:05 UTC, piasoratech commented on index.html
> +    <a href="#page"><img src="images/gototop.png" alt="ページトップに戻る" width="60" height="60"></a>
ここのリンクが`#`になっていないのと、画像のサイズはhtmlで指定するのではなくCSSで指定するようにしてください。

2020-07-19 01:05 UTC, piasoratech commented on index.html
> +</html>
ファイルの一番最後は改行を入れてください

2020-07-19 01:05 UTC, piasoratech commented on index.html
> +    </footer>
`header`,`main`,`footer`の外に要素があるのは良くないので、閉じタグの位置を考えましょう。

2020-07-19 05:40 UTC, ytaka0407 commented on index.html
> +    </footer>
foooter内に移動しました。

2020-07-19 05:42 UTC, ytaka0407 commented on index.html
> +    <a href="#page"><img src="images/gototop.png" alt="ページトップに戻る" width="60" height="60"></a>
各指定をcssに移動しました。同様の指定をしていた部分もすべてcssで設定に変更しました。

2020-07-19 05:42 UTC, ytaka0407 commented on index.html
> +</html>
以前のご指摘の際に入れてたと思ったのですが反映できていなかったかもしれません。
最新版では改行されていると思います。

2020-07-21 10:59 UTC, choimake reviewed
コメントしましたので確認お願いします。

- こちらのチェッカーで確認してみたところ、いくつかエラーがあったので、そちらの修正をお願いします。（html、css両方です）
まずエラーがない状態であることを自分で確認してから、レビューを依頼するようにしてください。
https://validator.w3.org/

- snsボタンはリンクにしてください。（元サイトもリンクになってますので）
<img width="260" alt="スクリーンショット 2020-07-21 19 39 54" src="https://user-images.githubusercontent.com/52233450/88046571-3cd97b80-cb8b-11ea-8d6e-816df476c973.png">

- fontの種類が元サイトと異なっています。せっかくなので合わせてみてください。

- 矢印のアイコンが文字にめり込んでます。
<img width="826" alt="スクリーンショット 2020-07-21 19 57 43" src="https://user-images.githubusercontent.com/52233450/88047389-824a7880-cb8c-11ea-8730-4ab6d17b6fc6.png">

- 下線部の位置が元サイトはもっと文字と近いです。
<img width="394" alt="スクリーンショット 2020-07-21 19 51 48" src="https://user-images.githubusercontent.com/52233450/88046885-b07b8880-cb8b-11ea-9b9a-b3920b23aaee.png">

- 文字の左のマークがないです。
<img width="172" alt="スクリーンショット 2020-07-21 19 53 12" src="https://user-images.githubusercontent.com/52233450/88047006-dd2fa000-cb8b-11ea-95aa-bce35cd75920.png">

- リンクを踏んだ後だと色が変わるようになっていますが、元サイトは変わらないような仕様になっています。こちら合わせてください。
<img width="601" alt="スクリーンショット 2020-07-21 19 53 54" src="https://user-images.githubusercontent.com/52233450/88047044-efa9d980-cb8b-11ea-8f93-8bb75925c114.png">

- snsボタンはリンクです。
<img width="355" alt="スクリーンショット 2020-07-21 19 52 57" src="https://user-images.githubusercontent.com/52233450/88047118-17993d00-cb8c-11ea-93a8-49e65cdad8f8.png">

- footer部分が元サイトと全然ちがいます。
<img width="1301" alt="スクリーンショット 2020-07-21 19 55 47" src="https://user-images.githubusercontent.com/52233450/88047195-326bb180-cb8c-11ea-8496-2d1b0d84cc1c.png">

2020-07-21 10:59 UTC, choimake commented on index.html
> +            <p class="copyright">Copyright&copy;Nomura Research Institute, Ltd. All rights reserved.</p>
copyrightはsmallタグを使いましょう。

2020-07-21 16:18 UTC, ytaka0407 commented on index.html
> +            <p class="copyright">Copyright&copy;Nomura Research Institute, Ltd. All rights reserved.</p>
指摘いただいた各所、修正しました。

2020-07-22 00:22 UTC, choimake reviewed
コメントしましたので確認お願いします。

- チェッカーにかけた際cssにエラーがありましたので、そちらのエラーを修正しておいてください。

2020-07-22 00:22 UTC, choimake commented on index.html
> +                    <a><img src="images/icon-linkedin.svg" alt="instagramシェア"></a>
ページ全体で言えることですが、snsボタンにマウスを当ててもリンクとして機能していませんでした。

2020-07-22 00:22 UTC, choimake commented on index.html
> +                    <span>&lt;<a href="#"> ビジネスモデルの特徴</a></span>
`&gt`は装飾用で書かれたものだと思いますが、装飾はcssで実装するようにしましょう。
こちらもページ全体です。

2020-07-22 03:53 UTC, ytaka0407 commented
コメントありがとうございます。自宅に帰ってから確認するのですが、ここは特殊文字の部分だったと記憶しています。
特殊文字もテキストではなく装飾の範疇に含まれますか？

2020-07-22 04:01 UTC, choimake commented on index.html
> +                    <span>&lt;<a href="#"> ビジネスモデルの特徴</a></span>
改めて見直したところ、どうやら文書的な意味で使われているようなので、この修正はなくていいです。
失礼しました。

2020-07-22 13:33 UTC, ytaka0407 commented on index.html
> +                    <a><img src="images/icon-linkedin.svg" alt="instagramシェア"></a>
cssバリデーションエラーと合わせて修正しました！

2020-07-23 03:10 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-07-23 03:10 UTC, choimake commented on style.css
> +}
ここだけインデントが他のところとズレています。

2020-07-23 03:10 UTC, choimake commented on style.css
> +}
`:`の後に、スペースがあったりなかったりとコードの書き方が異なっています。どちらかに統一してください。

2020-07-23 03:10 UTC, choimake commented on style.css
> +    transition:0.5s;
色の指定の際、小文字での指定と大文字での指定の表記が混在しています。
どちらかに統一した方が読みやすいので統一してください。

2020-07-23 03:10 UTC, choimake commented on style.css
> +}
末尾に改行いれておいてください。（理由はPOSIX）

2020-07-24 12:42 UTC, ytaka0407 commented on style.css
> +}
修正完了しました。

2020-07-24 12:42 UTC, ytaka0407 commented on style.css
> +}
スペースなしに統一しました。

2020-07-24 12:43 UTC, ytaka0407 commented on style.css
> +    transition:0.5s;
大文字表記に統一しました。

2020-07-24 12:44 UTC, ytaka0407 commented on style.css
> +}
何度もご指摘いただきすみません。。改行追記しました。

2020-07-24 13:25 UTC, choimake reviewed
コメントしましたので確認お願いします。
（ほぼOKなのですが、一箇所今の今まで見逃してました。申し訳ありませんが対応お願いします。）

2020-07-24 13:25 UTC, choimake commented on index.html
> +            <li><a href="#">情報セキュリティ対策についての宣言文</a></li>
`個人情報保護方針 個人情報の取扱いについて`はそれぞれ別のliタグで囲む必要があるかと

2020-07-24 13:30 UTC, ytaka0407 commented on index.html
> +            <li><a href="#">情報セキュリティ対策についての宣言文</a></li>
全く気づいていませんでした。。修正しました。

2020-07-24 13:31 UTC, choimake commented
LGTMです。次に進んでください。

2020-07-24 13:36 UTC, merged