htmlNkou
ytaka0407/y.takashima pull request #3
Opened 2020-08-16 11:39 UTC by ytaka0407

htmlN高の模写課題を作成しました。

2020-08-16 22:26 UTC, choimake reviewed
コメントしました。
全体的に細かいところまでよくできています。

ただいくつか気になる点があったので、そちら確認の上対応お願いします。

・fontの読み込みでエラー出てます。
<img width="406" alt="スクリーンショット 2020-08-17 7 11 51" src="https://user-images.githubusercontent.com/52233450/90345071-6afe8e00-e059-11ea-8ce1-729b86697c4a.png">

リンクを踏んだ後の、一部リンクの文字色が変わってます。
<img width="396" alt="スクリーンショット 2020-08-17 7 10 39" src="https://user-images.githubusercontent.com/52233450/90345094-81a4e500-e059-11ea-9913-dc4b833364d0.png">
<img width="1053" alt="スクリーンショット 2020-08-17 7 10 52" src="https://user-images.githubusercontent.com/52233450/90345123-9f724a00-e059-11ea-8ad3-657004a96b98.png">

・footerの文字色、オリジナルと異なる気がします。
<img width="1079" alt="スクリーンショット 2020-08-17 7 09 46" src="https://user-images.githubusercontent.com/52233450/90345058-591ceb00-e059-11ea-85f2-242c0756ac38.png">

2020-08-16 22:26 UTC, choimake commented on Nkou/style.css
> +}
例の改行のやつです。
エディタのフォーマッター使っているのであれば、設定を変更して改行が自動で挿入されるようにすると楽です。

2020-08-16 22:26 UTC, choimake commented on Nkou/style.css
> +    height: 100%;
「:」の後のスペースが入っていたり、なかったりしています。
コードのフォーマットは統一しましょう。

2020-08-16 22:26 UTC, choimake commented on Nkou/style.css
> +    font-weight:900;
インデントが乱れていますところがあります。修正してください。

2020-08-16 22:35 UTC, choimake commented
あとgitコメントに関してですが、文字数やその内容に関して大きく不備があるような印象はないです。

改善点があるとしたら、コミットメッセージには「何故、そのコードの変更をしたのか」という情報を含めると良いと思います（修正時など）

他の人のコードを読んで色々調査する時などがあるのですが、その時に「何故このような変更をしたのか」という情報はコミットメッセージやコード内のコメントでしか残すことはできません。
何故かあるかどうかで調査にかかる時間が大幅に変わってくるので、後からコードを読む人のために必要だと判断した場合は、是非「何故」の情報を残しておいて欲しいと思います。

また、以下にコミットメッセージについて参考記事のリンクを載せておきますので、ヒマな時にでも確認してみてください。

https://medium.com/@risacan/%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9-64aeadd92057

2020-08-17 16:21 UTC, ytaka0407 commented on Nkou/style.css
> +}
修正しました。Vscodeの更新かかった際に設定がオフになってしまっていたようです。。エディタの設定も直しました。

2020-08-17 16:24 UTC, ytaka0407 commented on Nkou/style.css
> +    height: 100%;
空白なしに統一しました。

2020-08-17 16:27 UTC, ytaka0407 commented on Nkou/style.css
> +    font-weight:900;
修正しました！

2020-08-18 12:39 UTC, piasoratech requested changes
見た目部分とても良くできていると思います。
フォントについてですが、今の読み込みの仕方で問題ありません。
N高本家の資材から読み込もうとしているので、もしかすると権限回りなどこちら側ではどうにもならない部分が影響しているかもしれません。

2020-08-18 12:39 UTC, piasoratech commented on Nkou/index.html
> +                </li>
ここの部分のhoverの挙動が本家と違います。
本家側はアルファベットの上部分にカーソルがあってもhover挙動をします。
![image](https://user-images.githubusercontent.com/57445698/90512811-ae601600-e199-11ea-9cc0-035023049ef9.png)

2020-08-19 02:59 UTC, ytaka0407 commented on Nkou/index.html
> +                </li>
挙動修正しました！

2020-08-19 12:40 UTC, choimake reviewed
コメントしました。

ほぼほぼOKなのですがちょろっと気になるところがあるので、確認と対応お願いします。

画面右にスクロールすると余白が発生します。
<img width="1440" alt="スクリーンショット 2020-08-19 21 23 21" src="https://user-images.githubusercontent.com/52233450/90635746-8d182c00-e264-11ea-8d50-06a0f00e85b6.png">

2020-08-19 12:40 UTC, choimake commented on Nkou/style.css
> +}*/
この手の不要になった処理のコメントは削除するようにしてください。
後からコード読んだ時にノイズになるので。
（いつか使う処理なのか、完全に不要なのか、良くわからないコードが残るのは可読性を下げます）

2020-08-19 14:17 UTC, ytaka0407 commented on Nkou/style.css
> +}*/
削除しました！

2020-08-19 14:41 UTC, ytaka0407 commented on Nkou/style.css
> +}*/
右端の余白について、ヘッダーの幅設定がおかしかったので修正し解消しました。

2020-08-19 15:04 UTC, choimake commented
対応ありがとうございました。LGTMです。

2020-08-19 15:05 UTC, choimake approved these changes
対応ありがとうございました。LGTMです。

2020-10-04 00:50 UTC, merged